### ISSUE TITLE
allow installation under python 3.8?

### ISSUE THREAD

**Issue by ltalirz** [kjappelbaum/oximachinerunner#31]
pypi package currently refuses to install under python 3.8

**Comment by kjappelbaum** [comment]
yes, i need to make a new release. Thanks!

**Comment by kjappelbaum** [comment]
<img width="1240" alt="Screen Shot 2020-12-15 at 12 43 41" src="https://user-images.githubusercontent.com/32935233/102210967-2c77c380-3ed3-11eb-9b35-870ce78b3224.png">

can you confirm?

**Comment by ltalirz** [comment]
confirmed; works with homebrew - some users may need to 
```
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Users/username/.brew/lib/
```
